update5

diff --git a/.github/workflow/cicd.yaml b/.github/workflow/cicd.yaml
--- a/.github/workflow/cicd.yaml
+++ b/.github/workflow/cicd.yaml
@@ -19,7 +19,20 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+      - name: Check Docker secrets
+        run: |
+          if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+            echo "DOCKER_USERNAME is missing"
+            exit 1
+          fi
 
+          if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
+            echo "DOCKER_PASSWORD is missing"
+            exit 1
+          fi
+
+          echo "Docker secrets exist"
+    
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
